var ALIASES = {};
ALIASES["artichoke_vfs"] = {};
ALIASES["mruby"] = {};
ALIASES["mruby_bin"] = {};
ALIASES["mruby_gems"] = {};
ALIASES["mruby_sys"] = {};
ALIASES["rirb"] = {};
ALIASES["spec_runner"] = {};
ALIASES["string_scan_bench"] = {};
