(function() {var implementors = {};
implementors["artichoke_backend"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/borrow/trait.Borrow.html\" title=\"trait core::borrow::Borrow\">Borrow</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/path/struct.Path.html\" title=\"struct std::path::Path\">Path</a>&gt; for <a class=\"struct\" href=\"artichoke_backend/fs/abs/struct.PathAbs.html\" title=\"struct artichoke_backend::fs::abs::PathAbs\">PathAbs</a>",synthetic:false,types:["artichoke_backend::fs::abs::PathAbs"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/borrow/trait.Borrow.html\" title=\"trait core::borrow::Borrow\">Borrow</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/path/struct.PathBuf.html\" title=\"struct std::path::PathBuf\">PathBuf</a>&gt; for <a class=\"struct\" href=\"artichoke_backend/fs/abs/struct.PathAbs.html\" title=\"struct artichoke_backend::fs::abs::PathAbs\">PathAbs</a>",synthetic:false,types:["artichoke_backend::fs::abs::PathAbs"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/borrow/trait.Borrow.html\" title=\"trait core::borrow::Borrow\">Borrow</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/path/struct.Path.html\" title=\"struct std::path::Path\">Path</a>&gt; for &amp;'a <a class=\"struct\" href=\"artichoke_backend/fs/abs/struct.PathAbs.html\" title=\"struct artichoke_backend::fs::abs::PathAbs\">PathAbs</a>",synthetic:false,types:["artichoke_backend::fs::abs::PathAbs"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/borrow/trait.Borrow.html\" title=\"trait core::borrow::Borrow\">Borrow</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/path/struct.PathBuf.html\" title=\"struct std::path::PathBuf\">PathBuf</a>&gt; for &amp;'a <a class=\"struct\" href=\"artichoke_backend/fs/abs/struct.PathAbs.html\" title=\"struct artichoke_backend::fs::abs::PathAbs\">PathAbs</a>",synthetic:false,types:["artichoke_backend::fs::abs::PathAbs"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
